### PR TITLE
Update agent target to 2.0.8

### PR DESCRIPTION
**Pull request by hdavidzhu**
Scripts should point to the latest version.

### CODE REVIEW

**Review by ostrowr — CHANGES_REQUESTED** [review]
you need to update the checksums as well :)

**Review by ostrowr — APPROVED** [review]
Unsure why the checks aren't running on this PR; hold up on merging this until I manage to run them

**Comment by ostrowr** [comment]
@hdavidzhu do you mind pushing up a noop commit to this branch? 

`git commit --allow-empty should work`

**Comment by hdavidzhu** [comment]
hmm no luck https://github.com/VantaInc/vanta-agent-scripts/pull/54

**Pull request closed without merging**
