### PR TITLE
bump download link agent version to 2.1.0

### PR DESCRIPTION
**Pull request by JHaoVanta**
## Changes
* tin

## Motivation
[sc-48801]

### CODE REVIEW

**Comment by ostrowr** [comment]
@JHaoVanta have we rolled 2.1.0 out to 100% of customers?

**Comment by JHaoVanta** [comment]
> @JHaoVanta have we rolled 2.1.0 out to 100% of customers?

yup!  we bumped up to 100 on 06/23 @ 10:20am-ish.  I've been monitoring logs/test flips/support tickets since

**Review by ostrowr — APPROVED** [review]
lgtm! But hoping we can roll out 2.1.1 soon :)

**Comment by JHaoVanta** [comment]
> lgtm! But hoping we can roll out 2.1.1 soon :)

2.1.2, technically, since we want to roll out the universal binary soon too!

**Pull request merged**
